version: '3.4'

services:
  ai:
    image: ai
    build:
      context: AI
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    networks:
      - mynetwork
    hostname: ai

  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - DATABASE=mongodb://database:27017/Social_media
      - DATABASE_PASSWORD=toan29102002
      - NODE_ENV=development
      - JWT_SECRET=nguyen-thanh-toan-cang-long-tra-vinh-my-web-node-js
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN= 90
      - EMAIL_USERNAME=c56efa3b971f88
      - EMAIL_PASSWORD=ae9ebfec15ac23
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_PORT=25
      - HORT_AI_API=http://ai:8000
    depends_on:
      - ai
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    hostname: backend

  frontend:
    image: client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - mynetwork
    hostname: frontend

  database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=Social_media
    networks:
      - mynetwork

networks:
  mynetwork:

